version: "3.8"

services:
  db:
    image: postgres:16
    container_name: irl-system
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: irl-system
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

volumes:
  postgres-data:
